apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher-monitoring
  namespace: cattle-monitoring-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher-monitoring
      version: "102.0.0+up40.1.2"
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
  values:
    prometheus:
      prometheusSpec:
        retention: 7d
        resources:
          requests:
            memory: 750Mi
            cpu: 750m
          limits:
            memory: 2Gi
            cpu: 1000m
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: default
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
        nodeSelector:
          node-role.caas.nci.bt.com/platform-worker: "true"
        tolerations:
          - key: node-role.caas.nci.bt.com/platform-worker
            operator: Equal
            value: "true"
            effect: NoExecute
    grafana:
      adminPassword: admin123
      persistence:
        enabled: true
        storageClassName: default
        size: 5Gi
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 500m
      nodeSelector:
        node-role.caas.nci.bt.com/platform-worker: "true"
      tolerations:
        - key: node-role.caas.nci.bt.com/platform-worker
          operator: Equal
          value: "true"
          effect: NoExecute
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
    alertmanager:
      alertmanagerSpec:
        retention: 120h
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 200Mi
            cpu: 200m
        nodeSelector:
          node-role.caas.nci.bt.com/platform-worker: "true"
        tolerations:
          - key: node-role.caas.nci.bt.com/platform-worker
            operator: Equal
            value: "true"
            effect: NoExecute
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: default
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
    nodeExporter:
      enabled: true
      nodeSelector:
        node-role.caas.nci.bt.com/platform-worker: "true"
      tolerations:
        - key: node-role.caas.nci.bt.com/platform-worker
          operator: Equal
          value: "true"
          effect: NoExecute
    kubeStateMetrics:
      enabled: true
      nodeSelector:
        node-role.caas.nci.bt.com/platform-worker: "true"
      tolerations:
        - key: node-role.caas.nci.bt.com/platform-worker
          operator: Equal
          value: "true"
          effect: NoExecute 