apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: loggings.logging.banzaicloud.io
spec:
  group: logging.banzaicloud.io
  names:
    kind: Logging
    listKind: LoggingList
    plural: loggings
    singular: logging
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flows.logging.banzaicloud.io
spec:
  group: logging.banzaicloud.io
  names:
    kind: Flow
    listKind: FlowList
    plural: flows
    singular: flow
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: outputs.logging.banzaicloud.io
spec:
  group: logging.banzaicloud.io
  names:
    kind: Output
    listKind: OutputList
    plural: outputs
    singular: output
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object 