apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring-prod
resources:
  - ../../base
configMapGenerator:
  - name: monitoring-config
    literals:
      - ENVIRONMENT=production
      - PROMETHEUS_RETENTION=30d
      - PROMETHEUS_STORAGE_SIZE=100Gi
      - PROMETHEUS_MEMORY_REQUEST=2Gi
      - PROMETHEUS_MEMORY_LIMIT=4Gi
      - PROMETHEUS_CPU_REQUEST=500m
      - PROMETHEUS_CPU_LIMIT=1000m
      - GRAFANA_PERSISTENCE_SIZE=10Gi
      - GRAFANA_MEMORY_REQUEST=512Mi
      - GRAFANA_MEMORY_LIMIT=1Gi
      - GRAFANA_CPU_REQUEST=250m
      - GRAFANA_CPU_LIMIT=500m
      - ALERTMANAGER_RETENTION=120h
      - ALERTMANAGER_STORAGE_SIZE=10Gi
      - ALERTMANAGER_MEMORY_REQUEST=256Mi
      - ALERTMANAGER_MEMORY_LIMIT=512Mi
      - ALERTMANAGER_CPU_REQUEST=100m
      - ALERTMANAGER_CPU_LIMIT=200m
      - STORAGE_CLASS=fast-ssd
secretGenerator:
  - name: monitoring-secrets
    envs:
      - ../../../examples/env.prod 