#!/bin/bash
# Configure zypper proxy settings for SL-Micro VM

echo "=========================================="
echo "Configure Zypper/RPM Proxy in SL-Micro VM"
echo "=========================================="
echo ""
echo "Run these commands INSIDE your SL-Micro VM"
echo ""
echo "1. Create proxy configuration file:"
echo "   sudo tee /etc/zypp/zypp.conf.d/proxy.conf <<EOF"
echo "proxy = http://your-proxy-server:port"
echo "proxy.user = username"
echo "proxy.password = password"
echo "EOF"
echo ""
echo "2. Or set environment variables for current session:"
echo "   export http_proxy=http://proxy.example.com:8080"
echo "   export https_proxy=http://proxy.example.com:8080"
echo "   export no_proxy=localhost,127.0.0.1"
echo ""
echo "3. For transactional-update (recommended for SL-Micro):"
echo "   sudo mkdir -p /etc/systemd/system/transactional-update.service.d/"
echo "   sudo tee /etc/systemd/system/transactional-update.service.d/proxy.conf <<EOF"
echo "[Service]"
echo "Environment=\"http_proxy=\${http_proxy}\""
echo "Environment=\"https_proxy=\${https_proxy}\""
echo "Environment=\"no_proxy=\${no_proxy}\""
echo "EOF"
echo ""
echo "4. Reload systemd and test:"
echo "   sudo systemctl daemon-reload"
echo "   sudo transactional-update pkg search jq"
echo ""
echo "=========================================="
echo "Quick Test (without proxy):"
echo "=========================================="
echo "   sudo transactional-update pkg search jq"
echo "   sudo transactional-update pkg install jq"
echo "   sudo reboot"


