#!/bin/bash
# Instructions and script to install JQ in SL-Micro VM

echo "=========================================="
echo "Installing JQ in SL-Micro VM"
echo "=========================================="
echo ""
echo "This script provides commands to run INSIDE your SL-Micro VM"
echo ""
echo "SSH into your VM first:"
echo "  ssh dave@10.0.2.15"
echo "  (or use the QEMU console)"
echo ""
echo "Then run these commands in the VM:"
echo ""
echo "1. Check if JQ is already installed:"
echo "   jq --version"
echo ""
echo "2. If not installed, check zypper repositories:"
echo "   sudo zypper repos"
echo ""
echo "3. Add Package Hub repository (if needed):"
echo "   sudo zypper addrepo https://download.opensuse.org/repositories/utilities/SLE_15_SP4/utilities.repo"
echo "   sudo zypper refresh"
echo ""
echo "4. Install JQ:"
echo "   sudo transactional-update pkg install jq"
echo "   sudo reboot"
echo ""
echo "5. After reboot, verify:"
echo "   jq --version"
echo ""
echo "=========================================="
echo "If you have proxy issues:"
echo "=========================================="
echo ""
echo "Configure proxy for transactional-update:"
echo ""
echo "sudo mkdir -p /etc/systemd/system/transactional-update.service.d/"
echo "sudo tee /etc/systemd/system/transactional-update.service.d/proxy.conf <<EOF"
echo "[Service]"
echo "Environment=\"http_proxy=http://your-proxy:8080\""
echo "Environment=\"https_proxy=http://your-proxy:8080\""
echo "Environment=\"no_proxy=localhost,127.0.0.1\""
echo "EOF"
echo "sudo systemctl daemon-reload"
echo ""
echo "Then retry the installation."


