apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher-logging
  namespace: cattle-logging-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher-logging
      version: 3.9.400
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
  values:
    global:
      cattle:
        systemDefaultRegistry: ""
      rke2Enabled: true
    
    # Fluentd configuration
    fluentd:
      persistence:
        enabled: true
        size: 20Gi
        storageClassName: standard
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m
      buffer:
        chunkLimitSize: 1M
        totalLimitSize: 200M
        flushInterval: 10s
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
    
    # Elasticsearch configuration
    elasticsearch:
      enabled: true
      replicas: 2
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 2Gi
          cpu: 1000m
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
          storageClassName: standard
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
    
    # Kibana configuration
    kibana:
      enabled: true
      replicas: 1
      resources:
        requests:
          memory: 256Mi
          cpu: 125m
        limits:
          memory: 512Mi
          cpu: 250m
      persistence:
        enabled: true
        size: 5Gi
        storageClassName: standard
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
    
    # Fluent Bit configuration
    fluentbit:
      enabled: true
      resources:
        requests:
          memory: 64Mi
          cpu: 25m
        limits:
          memory: 128Mi
          cpu: 50m
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
    
    # Log aggregation configuration
    aggregation:
      enabled: true
      resources:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 100m
    
    # Network Policies
    networkPolicy:
      enabled: true
      ingressRules:
        - from:
          - namespaceSelector:
              matchLabels:
                name: cattle-logging-system
          ports:
          - port: 9200
            protocol: TCP
          - port: 5601
            protocol: TCP
      egressRules:
        - to:
          - namespaceSelector: {}
          ports:
          - port: 53
            protocol: UDP
          - port: 53
            protocol: TCP 