apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring-dev
  namespace: fleet-local
spec:
  repo: https://github.com/dlawton20-devops/gitops
  branch: dev
  paths:
  - monitoring
  targets:
  - clusterSelector:
      matchLabels:
        env: dev 