# GitLab Repository Invitation Configuration
# This file defines users (by email only) and repositories for invitation automation

gitlab:
  url: "https://gitlab.example.com"  # Replace with your GitLab URL
  token: "your-gitlab-token-here"    # Replace with your GitLab token

# Users to invite (email addresses only)
users:
  - email: "alice.dev@example.com"
  - email: "bob.dev@example.com"
  - email: "charlie.dev@example.com"
  - email: "diana.dev@example.com"
  - email: "eve.dev@example.com"
  - email: "frank.dev@example.com"

# Repositories to invite users to
# All users get Developer access (level 30) to all repositories
# Access levels: 10=Guest, 20=Reporter, 30=Developer, 40=Maintainer, 50=Owner
repositories:
  # Option 1: By repository name (searches all projects)
  - name: "frontend-app"
    access_level: 30  # Developer
  
  # Option 2: By full project path (group/project)
  - name: "my-group/backend-api"
    access_level: 30  # Developer
  
  # Option 3: By project ID (numeric ID)
  - name: "123"  # Project ID
    access_level: 30  # Developer
  
  # Option 4: By full GitLab URL path
  - name: "my-org/my-group/mobile-app"
    access_level: 30  # Developer
  
  - name: "devops-tools"
    access_level: 30  # Developer
  
  - name: "documentation"
    access_level: 30  # Developer
  
  - name: "testing-framework"
    access_level: 30  # Developer
  
  - name: "shared-libraries"
    access_level: 30  # Developer
  
  - name: "infrastructure"
    access_level: 30  # Developer
  
  - name: "monitoring"
    access_level: 30  # Developer
  
  - name: "security-tools"
    access_level: 30  # Developer
