apiVersion: v2
name: rook-ceph
description: A Helm chart for Rook Ceph storage orchestrator
type: application
version: 0.1.0
appVersion: "1.12.0"
keywords:
  - storage
  - ceph
  - rook
  - kubernetes
home: https://rook.io
sources:
  - https://github.com/rook/rook
maintainers:
  - name: Rook Maintainers
    email: rook-maintainers@googlegroups.com
 