apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - helm-repositories.yaml
  - harbor-auth.yaml
  - monitoring/
  - logging/

commonLabels:
  app.kubernetes.io/part-of: shared-infrastructure
  managed-by: flux 