apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-crds.yaml
  - grafana-crds.yaml
  - alertmanager-crds.yaml

# CRDs should be deployed first, before any other resources
# This ensures the custom resources are available when the Helm charts are deployed 