apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - applications/
  - services/
  - configmaps/

configMapGenerator:
  - name: tenant-config
    literals:
      - tenant-name=tenant1
      - max-replicas=10
      - min-replicas=2

commonLabels:
  tenant: tenant1
  app.kubernetes.io/part-of: tenant1-apps 