apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: openstack-cluster
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    services:
      cidrBlocks: ["10.128.0.0/12"]
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: openstack-cluster-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OpenStackCluster
    name: openstack-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: openstack-cluster
spec:
  identityRef:
    kind: Secret
    name: openstack-credentials
  cloudName: openstack
  controlPlaneEndpoint:
    host: ""
    port: 6443 