#!/bin/bash
# Example Workflow Script - Manual Execution Guide
# This script shows the commands you would run manually
# DO NOT RUN THIS SCRIPT DIRECTLY - Use it as a reference

set -e

echo "=========================================="
echo "Rook Ceph Velero Backup/Restore Workflow"
echo "=========================================="
echo ""
echo "This is a reference script showing manual commands."
echo "Copy and paste commands as needed."
echo ""
echo "Press Ctrl+C to exit, or wait 5 seconds to continue..."
sleep 5

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo ""
echo -e "${GREEN}=== STEP 1: Install Velero on Source Cluster ===${NC}"
echo ""
echo "# Create credentials file first:"
echo "cat > credentials-velero <<EOF"
echo "[default]"
echo "aws_access_key_id=minioadmin"
echo "aws_secret_access_key=minioadmin123"
echo "EOF"
echo ""
echo "# Install Velero:"
echo "./scripts/install-velero.sh \\"
echo "  --s3-endpoint https://minio.velero.svc.cluster.local:9000 \\"
echo "  --credentials ./credentials-velero"
echo ""
echo "# Or manually:"
echo "velero install \\"
echo "  --provider aws \\"
echo "  --plugins velero/velero-plugin-for-aws:v1.8.0 \\"
echo "  --bucket velero-backups \\"
echo "  --secret-file ./credentials-velero \\"
echo "  --use-volume-snapshots=false \\"
echo "  --backup-location-config region=minio,s3ForcePathStyle=\"true\",s3Url=https://minio.velero.svc.cluster.local:9000 \\"
echo "  --use-node-agent \\"
echo "  --default-volumes-to-fs-backup"
echo ""
read -p "Press Enter to continue to Step 2..."

echo ""
echo -e "${GREEN}=== STEP 2: Create Backup ===${NC}"
echo ""
echo "# Create full backup:"
echo "./scripts/create-backup.sh --type full"
echo ""
echo "# Or manually:"
echo "BACKUP_NAME=\"rook-ceph-backup-\$(date +%Y%m%d-%H%M%S)\""
echo "velero backup create \$BACKUP_NAME \\"
echo "  --include-namespaces=rook-ceph,production \\"
echo "  --include-cluster-resources=true \\"
echo "  --default-volumes-to-fs-backup \\"
echo "  --wait"
echo ""
echo "# Check backup status:"
echo "velero backup get"
echo "velero backup describe \$BACKUP_NAME"
echo ""
read -p "Press Enter to continue to Step 3..."

echo ""
echo -e "${GREEN}=== STEP 3: Verify Backup ===${NC}"
echo ""
echo "# Verify backup:"
echo "./scripts/verify-backup.sh --backup <backup-name>"
echo ""
echo "# Or manually:"
echo "velero backup describe <backup-name>"
echo "velero backup logs <backup-name>"
echo ""
read -p "Press Enter to continue to Step 4..."

echo ""
echo -e "${GREEN}=== STEP 4: Install Velero on Target Cluster ===${NC}"
echo ""
echo "# Switch to target cluster context:"
echo "kubectl config use-context <target-cluster-context>"
echo ""
echo "# Install Velero (same as Step 1, pointing to same backup storage):"
echo "./scripts/install-velero.sh \\"
echo "  --s3-endpoint https://minio.velero.svc.cluster.local:9000 \\"
echo "  --credentials ./credentials-velero"
echo ""
echo "# Verify backups are visible:"
echo "velero backup get"
echo ""
read -p "Press Enter to continue to Step 5..."

echo ""
echo -e "${GREEN}=== STEP 5: Restore Backup ===${NC}"
echo ""
echo "# Restore from backup:"
echo "./scripts/restore-backup.sh --backup <backup-name>"
echo ""
echo "# Or manually:"
echo "RESTORE_NAME=\"restore-\$(date +%Y%m%d-%H%M%S)\""
echo "velero restore create \$RESTORE_NAME \\"
echo "  --from-backup <backup-name> \\"
echo "  --include-cluster-resources=true \\"
echo "  --wait"
echo ""
echo "# Check restore status:"
echo "velero restore get"
echo "velero restore describe \$RESTORE_NAME"
echo ""
read -p "Press Enter to continue to Step 6..."

echo ""
echo -e "${GREEN}=== STEP 6: Verify Restore ===${NC}"
echo ""
echo "# Check Ceph cluster:"
echo "kubectl get cephcluster -n rook-ceph"
echo "kubectl get pods -n rook-ceph"
echo ""
echo "# Check PVCs:"
echo "kubectl get pvc -A"
echo ""
echo "# Check applications:"
echo "kubectl get pods -A"
echo "kubectl get storageclass"
echo ""
echo ""
echo -e "${GREEN}=========================================="
echo "Workflow Complete!"
echo "==========================================${NC}"
echo ""
echo "For more details, see:"
echo "  - QUICK_START.md - Step-by-step guide"
echo "  - docs/BACKUP_GUIDE.md - Backup details"
echo "  - docs/RESTORE_GUIDE.md - Restore details"
echo "  - docs/TROUBLESHOOTING.md - Common issues"
echo ""

