apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher-monitoring
  namespace: cattle-monitoring-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher-monitoring
      version: 102.0.0+up40.1.2
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
  values:
    global:
      cattle:
        systemDefaultRegistry: ""
      rke2Enabled: true
    
    # Prometheus configuration
    prometheus:
      prometheusSpec:
        evaluationInterval: 30s
        scrapeInterval: 30s
        retention: 7d
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
              storageClassName: standard
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
          limits:
            memory: 2Gi
            cpu: 500m
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          fsGroup: 65534
    
    # Grafana configuration
    grafana:
      enabled: true
      persistence:
        enabled: true
        size: 5Gi
        storageClassName: standard
      resources:
        requests:
          memory: 256Mi
          cpu: 125m
        limits:
          memory: 512Mi
          cpu: 250m
      securityContext:
        runAsNonRoot: true
        runAsUser: 472
        fsGroup: 472
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            updateIntervalSeconds: 10
            allowUiUpdates: true
            options:
              path: /var/lib/grafana/dashboards/default
    
    # AlertManager configuration
    alertmanager:
      alertmanagerSpec:
        retention: 48h
        storage:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
              storageClassName: standard
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          fsGroup: 65534
    
    # Node Exporter
    nodeExporter:
      enabled: true
      resources:
        requests:
          memory: 64Mi
          cpu: 25m
        limits:
          memory: 128Mi
          cpu: 50m
    
    # Kube State Metrics
    kubeStateMetrics:
      enabled: true
      resources:
        requests:
          memory: 64Mi
          cpu: 25m
        limits:
          memory: 128Mi
          cpu: 50m
    
    # Service Monitor for Rancher
    additionalScrapeConfigs:
      - job_name: 'rancher'
        static_configs:
          - targets: ['rancher-webhook.cattle-system.svc:8443']
        metrics_path: /metrics
        scheme: https
        tls_config:
          insecure_skip_verify: true
    
    # Network Policies
    networkPolicy:
      enabled: true
      ingressRules:
        - from:
          - namespaceSelector:
              matchLabels:
                name: cattle-monitoring-system
          ports:
          - port: 9090
            protocol: TCP
          - port: 9091
            protocol: TCP
      egressRules:
        - to:
          - namespaceSelector: {}
          ports:
          - port: 53
            protocol: UDP
          - port: 53
            protocol: TCP 